Fe 8 calendar detail insert
Jefdeniel/Work5 pull request #63
Opened 2024-05-16 17:21 UTC by Kyandroo

2024-05-16 17:56 UTC, Jefdeniel requested changes

2024-05-16 17:56 UTC, Jefdeniel commented on frontend/src/components/calendar/CalendarCard/CalendarCard.tsx
> +            <Icon src={userImgSrc} alt={userImgAlt} />
add fallback

2024-05-16 17:56 UTC, Jefdeniel commented on frontend/src/components/calendar/CalendarCard/CalendarCard.tsx
> +            <Icon src={userImgSrc} alt={userImgAlt} />
allready loop over a couple of items to make it easier in the future

2024-05-16 17:56 UTC, Jefdeniel commented on frontend/src/components/layout/Navigation/CalendarNavigation.tsx
> +            {t('general:navigation.title'.toString())}
is toString() necessary? Doesn't it also work without?

2024-05-16 18:26 UTC, Kyandroo commented on frontend/src/components/ui/Icon/SvgIcons.tsx
> +        width="13"
Possible, but what when later on we want to use them somewhere else?

2024-05-16 18:29 UTC, Kyandroo commented on frontend/src/components/ui/EventCard/Card.scss
For the moment, still has to be styled

2024-05-17 07:42 UTC, Kyandroo commented on frontend/src/pages/Calendar/Calendar.tsx
> +      <div>{!isLoading ? '' : 'Loading...'}</div>
Do you mean like this?
<div>{!isLoading ? '' : <Spinner />}</div>

2024-05-17 07:42 UTC, Kyandroo commented on frontend/src/pages/Calendar/Calendar.tsx
> +      <div>{!isLoading ? '' : 'Loading...'}</div>
Do you mean like this?
`<div>{!isLoading` ? '' : <Spinner />}</div>`

2024-05-17 07:43 UTC, Kyandroo commented on frontend/src/pages/Calendar/Calendar.tsx
> +      <div>{!isLoading ? '' : 'Loading...'}</div>
Do you mean changing the 'loading...' to the Spinner component?

2024-05-17 09:54 UTC, merged